version: '3'


services:

  server:
    build: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - server_modules:/usr/local/lib/python3.6/site-packages
      - server_bin:/usr/local/bin

  client:
    build: client
    ports:
      - "8080:8080"
    environment:
        NODE_ENVIRONMENT: production
        PORT: 8080
    links:
      - server
    volumes:
        - ./client:/app
        - client_modules:/app/node_modules


volumes:
    server_modules:
        external: false
    server_bin:
        external: false
    client_modules:
        external: false
